#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="Hack Nerd Font" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3 # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
cd $HOME/.config/sketchybar/helper && make
$HOME/.config/sketchybar/helper/helper $HELPER > /dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# Setting up the general bar appearance and default values
sketchybar --bar     height=27                                         \
                     color=$BAR_COLOR                                  \
                     shadow=on                                         \
                     position=top                                      \
                     sticky=on                                         \
                     font_smoothing=on                                  \
                     padding_right=10                                  \
                     padding_left=20                                  \
                     corner_radius=9                                   \
                     y_offset=0                                       \
                     margin=0                                         \
                     blur_radius=20                                    \
                     notch_width=0                                     \
		     topmost=false                                     \
                                                                       \
           --default updates=when_shown                                \
	             drawing=on                                        \
                     icon.font="$FONT:Regular:20.0"                    \
                     icon.padding_left=$PADDINGS                       \
                     icon.padding_right=$PADDINGS                      \
		     icon.background.color=$TRANSPARENT                \
                     label.font="$FONT:Bold:13.0"                      \
                     label.color=$LABEL_COLOR                          \
                     label.padding_left=$PADDINGS                      \
                     label.padding_right=$PADDINGS                     \
                     background.padding_right=$PADDINGS                \
                     background.padding_left=$PADDINGS                 \
                     background.height=30                              \
                     background.corner_radius=9                        \
                     popup.background.border_width=2                   \
                     popup.background.corner_radius=9                  \
                     popup.background.border_color=$POPUP_BORDER_COLOR \
                     popup.background.color=$POPUP_BACKGROUND_COLOR    \
                     popup.background.shadow.drawing=on
sketchybar -m --add item battery right \
              --set battery update_freq=3 \
              --set battery script="~/.config/sketchybar/plugins/power.sh" \
              --set battery icon=
# source "$ITEM_DIR/.sh"
# Left
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"
# Center
source "$ITEM_DIR/spotify.sh"
# Right
source "$ITEM_DIR/divider.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/calendar.sh"
# source "$ITEM_DIR/cpu.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
