local builtin = require('telescope.builtin')
vim.keymap.set('n', 'ff', builtin.find_files, {})
vim.keymap.set('n', 'lg', builtin.live_grep, {})
vim.keymap.set('n', 'fb', builtin.buffers, {})
vim.keymap.set('n', 'fh', builtin.help_tags, {})
vim.keymap.set('n', 'ld', builtin.lsp_definitions, {})
vim.keymap.set('n', 'ds', builtin.lsp_document_symbols, {})
vim.keymap.set('n', 'ts', builtin.treesitter, {})
